version: '2'
services:
  lb:
    image: rancher/lb-service-haproxy:v0.9.1
    ports:
    - 7000:7000/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: balancer=true
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
